list.of.packages <- c(
"sessioninfo",
"ggplot2",
"reshape2",
"GGally",
"ggridges",
"plyr",
"dplyr",
"tidyr",
"tidyverse",
"Cairo",
"matrixStats",
"forcats",
"hardhat",
"grid",
"gridExtra",
"ggExtra",
"egg",
"devtools",
"ggtree",
"castor",
"treeio",
"TreeTools",
"stringr",
"cowplot",
"ggpubr",
"gggenes"                     )
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
